-- Load all assets at once. Yes, this is stupid. Leave me alone.
sprites = {}
sprites.blank = love.graphics.newImage('sprites/blank.png')
sprites.playerSheet = love.graphics.newImage('sprites/player/default/red/full.png')
sprites.playerHead = love.graphics.newImage('sprites/player/default/red/head.png')
sprites.playerShadow = love.graphics.newImage('sprites/player/playerShadow.png')
sprites.playerAim = love.graphics.newImage('sprites/player/aim.png')
sprites.playerAimCursor = love.graphics.newImage('sprites/player/aimCursor.png')
sprites.playerAimCursor2 = love.graphics.newImage('sprites/player/aimCursor2.png')
sprites.playerRedIcon = love.graphics.newImage('sprites/player/playerRedIcon.png')

sprites.player = {}
sprites.player.eyes = love.graphics.newImage('sprites/player2/red/eyes.png')
sprites.player.head = love.graphics.newImage('sprites/player2/red/head.png')
sprites.player.body = love.graphics.newImage('sprites/player2/red/body.png')
sprites.player.arm = love.graphics.newImage('sprites/player2/red/arm.png')
sprites.player.armHold = love.graphics.newImage('sprites/player2/red/arm.png')
sprites.player.belly = love.graphics.newImage('sprites/player2/red/belly.png')
sprites.player.feet = love.graphics.newImage('sprites/player2/red/feet.png')
sprites.player.full = love.graphics.newImage('sprites/player2/red/full.png')

sprites.num = {}
sprites.num[0] = love.graphics.newImage('fonts/boxy-bold/indiv/0.png')
sprites.num[1] = love.graphics.newImage('fonts/boxy-bold/indiv/1.png')
sprites.num[2] = love.graphics.newImage('fonts/boxy-bold/indiv/2.png')
sprites.num[3] = love.graphics.newImage('fonts/boxy-bold/indiv/3.png')
sprites.num[4] = love.graphics.newImage('fonts/boxy-bold/indiv/4.png')
sprites.num[5] = love.graphics.newImage('fonts/boxy-bold/indiv/5.png')
sprites.num[6] = love.graphics.newImage('fonts/boxy-bold/indiv/6.png')
sprites.num[7] = love.graphics.newImage('fonts/boxy-bold/indiv/7.png')
sprites.num[8] = love.graphics.newImage('fonts/boxy-bold/indiv/8.png')
sprites.num[9] = love.graphics.newImage('fonts/boxy-bold/indiv/9.png')
sprites.num.minus = love.graphics.newImage('fonts/boxy-bold/indiv/minus.png')
sprites.num.frames = {}
sprites.num.frames[0] = love.graphics.newImage('fonts/boxy-bold/indiv/frames/0.png')
sprites.num.frames[1] = love.graphics.newImage('fonts/boxy-bold/indiv/frames/1.png')
sprites.num.frames[2] = love.graphics.newImage('fonts/boxy-bold/indiv/frames/2.png')
sprites.num.frames[3] = love.graphics.newImage('fonts/boxy-bold/indiv/frames/3.png')
sprites.num.frames[4] = love.graphics.newImage('fonts/boxy-bold/indiv/frames/4.png')
sprites.num.frames[5] = love.graphics.newImage('fonts/boxy-bold/indiv/frames/5.png')
sprites.num.frames[6] = love.graphics.newImage('fonts/boxy-bold/indiv/frames/6.png')
sprites.num.frames[7] = love.graphics.newImage('fonts/boxy-bold/indiv/frames/7.png')
sprites.num.frames[8] = love.graphics.newImage('fonts/boxy-bold/indiv/frames/8.png')
sprites.num.frames[9] = love.graphics.newImage('fonts/boxy-bold/indiv/frames/9.png')
sprites.num.frames.minus = love.graphics.newImage('fonts/boxy-bold/indiv/frames/minus.png')
sprites.effects = {} 
sprites.effects.petal = love.graphics.newImage('sprites/effects/petal.png')
sprites.effects.leaf = love.graphics.newImage('sprites/effects/leaf.png')
sprites.effects.pixel = love.graphics.newImage('sprites/effects/pixel.png')
sprites.effects.darkness = love.graphics.newImage('sprites/effects/darkness-wide.png')
sprites.effects.darknessSm = love.graphics.newImage('sprites/effects/darkness-small-wide.png')
sprites.effects.slice = love.graphics.newImage('sprites/effects/slice.png')
sprites.effects.sliceAnim = love.graphics.newImage('sprites/effects/sliceAnim.png')
sprites.effects.sliceAnimDist = love.graphics.newImage('sprites/effects/sliceAnimDist.png')
sprites.effects.sliceBigAnim = love.graphics.newImage('sprites/effects/sliceBigAnim.png')
sprites.effects.stabAnim = love.graphics.newImage('sprites/effects/stabAnim.png')
sprites.effects.spinSlice = love.graphics.newImage('sprites/effects/spinSlice.png')
sprites.effects.explosion = love.graphics.newImage('sprites/effects/explosion3.png')
sprites.effects.explosion4 = love.graphics.newImage('sprites/effects/explosion4.png')
sprites.effects.poisonSmoke = love.graphics.newImage('sprites/effects/poisonSmoke.png')
sprites.effects.spark = love.graphics.newImage('sprites/effects/spark.png')
sprites.effects.stunStars = love.graphics.newImage('sprites/effects/stun-stars.png')
sprites.effects.rock = love.graphics.newImage('sprites/effects/rock.png')
sprites.effects.canHold = love.graphics.newImage('sprites/effects/canHold.png')
sprites.effects.fuseSmoke = love.graphics.newImage('sprites/effects/fuseSmoke.png')
sprites.effects.scorch = love.graphics.newImage('sprites/effects/scorch3.png')
sprites.effects.triangleScorch = love.graphics.newImage('sprites/effects/scorch/triangle.png')
sprites.effects.darkMagicB = love.graphics.newImage('sprites/effects/darkMagicB.png')
sprites.effects.darkMagicW = love.graphics.newImage('sprites/effects/darkMagicW.png')
sprites.effects.death = love.graphics.newImage('sprites/effects/death.png')
sprites.effects.arrowShadow = love.graphics.newImage('sprites/effects/shadows/arrow.png')
sprites.effects.bombShadow = love.graphics.newImage('sprites/effects/shadows/bomb.png')
sprites.effects.boomerangShadow = love.graphics.newImage('sprites/effects/shadows/boomerang.png')
sprites.effects.treeShadow = love.graphics.newImage('sprites/effects/shadows/tree.png')
sprites.effects.fireball = love.graphics.newImage('sprites/effects/fireball.png')
sprites.effects.ripple = love.graphics.newImage('sprites/effects/ripple.png')
sprites.effects.rainRipple = love.graphics.newImage('sprites/effects/rainRipple.png')
sprites.effects.cloudShadow = love.graphics.newImage('sprites/effects/cloudShadow.png')
sprites.effects.rain = love.graphics.newImage('sprites/effects/rain.png')
sprites.effects.snow = love.graphics.newImage('sprites/effects/snow.png')
sprites.effects.portal = love.graphics.newImage('sprites/effects/portal/portal-g.png')
sprites.effects.portal2 = love.graphics.newImage('sprites/effects/portal/portal2.png')
sprites.effects.portal3 = love.graphics.newImage('sprites/effects/portal/portal3.png')
sprites.effects.plantCut = love.graphics.newImage('sprites/effects/plant-cut.png')
sprites.effects.barLightning = love.graphics.newImage('sprites/effects/electric/barLightning.png')
sprites.effects.lightning = love.graphics.newImage('sprites/effects/electric/lightning.png')
sprites.effects.shock = love.graphics.newImage('sprites/effects/electric/shock.png')
sprites.effects.smallCharge = love.graphics.newImage('sprites/effects/electric/small-charge.png')
sprites.effects.electricOrb = love.graphics.newImage('sprites/effects/electric/orb.png')
sprites.effects.electricField = love.graphics.newImage('sprites/effects/electric/field.png')
sprites.effects.electricHit = love.graphics.newImage('sprites/effects/electric/elecHit.png')
sprites.effects.groundIce1 = love.graphics.newImage('sprites/effects/spells/groundIce1.png')
sprites.effects.groundIce2 = love.graphics.newImage('sprites/effects/spells/groundIce2.png')
sprites.effects.groundIce3 = love.graphics.newImage('sprites/effects/spells/groundIce3.png')
sprites.effects.iceBlast = love.graphics.newImage('sprites/effects/spells/ice-blast.png')
sprites.effects.iceShard = love.graphics.newImage('sprites/effects/spells/ice-shard.png')
sprites.effects.heal = love.graphics.newImage('sprites/effects/spells/heal.png')
sprites.effects.healWind = love.graphics.newImage('sprites/effects/spells/heal-wind.png')
sprites.effects.fireRing = love.graphics.newImage('sprites/effects/spells/fire/fire-ring-half.png')
sprites.effects.fireStatus = love.graphics.newImage('sprites/effects/fire/fireStatus.png')
sprites.effects.flameAttack = love.graphics.newImage('sprites/effects/fire/flameAttack.png')
sprites.effects.sparkle = love.graphics.newImage('sprites/effects/sparkle.png')
sprites.effects.spawnMagic = love.graphics.newImage('sprites/effects/spawnMagic.png')
sprites.effects.magicExplosion = love.graphics.newImage('sprites/effects/magicExplosion.png')
sprites.effects.eyeBall = love.graphics.newImage('sprites/effects/eyeBall.png')
sprites.effects.eyeIrisSmall = love.graphics.newImage('sprites/effects/eyeIrisSmall.png')
sprites.effects.apple = love.graphics.newImage('sprites/effects/apple.png')
sprites.effects.shadows = {}
sprites.effects.shadows.arrow = love.graphics.newImage('sprites/effects/shadows/arrow.png')
sprites.effects.shadows.bomb = love.graphics.newImage('sprites/effects/shadows/bomb.png')
sprites.effects.shadows.boomerang = love.graphics.newImage('sprites/effects/shadows/boomerang.png')
sprites.effects.shadows.tree = love.graphics.newImage('sprites/effects/shadows/tree.png')
sprites.effects.shadows.stump = love.graphics.newImage('sprites/effects/shadows/stump.png')
sprites.effects.shadows.bigTree = love.graphics.newImage('sprites/effects/shadows/bigTree.png')
sprites.effects.shadows.lob = love.graphics.newImage('sprites/effects/shadows/lob.png')
sprites.effects.shadows.enemySm = love.graphics.newImage('sprites/effects/shadows/enemySm.png')
sprites.effects.shadows.enemyL = love.graphics.newImage('sprites/effects/shadows/enemyL.png')
sprites.effects.shadows.portal = love.graphics.newImage('sprites/effects/shadows/portal.png')
sprites.effects.shadows.plant = love.graphics.newImage('sprites/effects/shadows/plant.png')
sprites.effects.shadows.boss = love.graphics.newImage('sprites/effects/shadows/boss.png')
sprites.effects.shadows.player = love.graphics.newImage('sprites/effects/shadows/player.png')
sprites.effects.shadows.small = love.graphics.newImage('sprites/effects/shadows/small.png')
sprites.effects.shadows.medium = love.graphics.newImage('sprites/effects/shadows/medium.png')
sprites.effects.shadows.mediumTall = love.graphics.newImage('sprites/effects/shadows/mediumTall.png')
sprites.effects.shadows.rock = love.graphics.newImage('sprites/effects/shadows/rock.png')
sprites.effects.shadows.pillar = love.graphics.newImage('sprites/effects/shadows/pillar.png')
sprites.effects.shadows.storyPortal = love.graphics.newImage('sprites/effects/shadows/portalShadow.png')
sprites.effects.shadows.rockSpike = love.graphics.newImage('sprites/effects/shadows/rockSpikeShadow.png')
sprites.effects.shadows.chestSmall = love.graphics.newImage('sprites/effects/shadows/chestSmall.png')
sprites.effects.shadows.chestBig = love.graphics.newImage('sprites/effects/shadows/chestBig.png')
sprites.effects.shadows.giant = love.graphics.newImage('sprites/effects/shadows/bigTree.png')
sprites.effects.shadows.longWeapon = love.graphics.newImage('sprites/effects/shadows/longWeapon.png')
sprites.effects.shadows.tiny = love.graphics.newImage('sprites/effects/shadows/tiny.png')
sprites.effects.shadows.campfire = love.graphics.newImage('sprites/effects/shadows/campfire.png')
sprites.effects.smoke = {}
sprites.effects.smoke.chimney = love.graphics.newImage('sprites/effects/smoke/chimney.png')
sprites.effects.smoke.small = love.graphics.newImage('sprites/effects/smoke/small.png')
sprites.effects.smoke.smallTinyPoison = love.graphics.newImage('sprites/effects/smoke/smallTinyPoison.png')
sprites.effects.grass = {}
sprites.effects.grass[1] = love.graphics.newImage('sprites/effects/grass/grass1.png')
sprites.effects.grass[2] = love.graphics.newImage('sprites/effects/grass/grass2.png')
sprites.effects.grass[3] = love.graphics.newImage('sprites/effects/grass/grass3.png')
sprites.effects.minGrass = {}
sprites.effects.minGrass[1] = love.graphics.newImage('sprites/effects/grass/min1.png')
sprites.effects.minGrass[2] = love.graphics.newImage('sprites/effects/grass/min2.png')
sprites.effects.minGrass[3] = love.graphics.newImage('sprites/effects/grass/min3.png')
sprites.effects.vine = {}
sprites.effects.vine[1] = love.graphics.newImage('sprites/effects/grass/vine1.png')
sprites.effects.vine[2] = love.graphics.newImage('sprites/effects/grass/vine2.png')
sprites.effects.vine[3] = love.graphics.newImage('sprites/effects/grass/vine3.png')
sprites.effects.rock = {}
sprites.effects.rock[1] = love.graphics.newImage('sprites/effects/rocks/rock1.png')
sprites.effects.rock[2] = love.graphics.newImage('sprites/effects/rocks/rock2.png')
sprites.effects.rockGrey = {}
sprites.effects.rockGrey[1] = love.graphics.newImage('sprites/effects/rocks/rockGrey1.png')
sprites.effects.rockGrey[2] = love.graphics.newImage('sprites/effects/rocks/rockGrey2.png')
sprites.effects.rockSpike = love.graphics.newImage('sprites/effects/rocks/rockSpike.png')
sprites.effects.shard = {}
sprites.effects.shard[1] = love.graphics.newImage('sprites/effects/debris/shard1.png')
sprites.effects.shard[2] = love.graphics.newImage('sprites/effects/debris/shard2.png')
sprites.effects.steelShard = {}
sprites.effects.steelShard[1] = love.graphics.newImage('sprites/effects/debris/steelShard1.png')
sprites.effects.steelShard[2] = love.graphics.newImage('sprites/effects/debris/steelShard2.png')
sprites.effects.blobs = {}
sprites.effects.blobs.blob1 = love.graphics.newImage('sprites/effects/blobs/blob1.png')
sprites.effects.blobs.blob2 = love.graphics.newImage('sprites/effects/blobs/blob2.png')
sprites.effects.blobs.blob3 = love.graphics.newImage('sprites/effects/blobs/blob3.png')
sprites.effects.blobs.blob4 = love.graphics.newImage('sprites/effects/blobs/blob4.png')

sprites.debris = {}
sprites.debris.wood1 = love.graphics.newImage('sprites/effects/debris/wood1.png')
sprites.debris.scrap1 = love.graphics.newImage('sprites/effects/debris/scrap1.png')
sprites.debris.scrap2 = love.graphics.newImage('sprites/effects/debris/scrap2.png')
sprites.debris.scrap3 = love.graphics.newImage('sprites/effects/debris/scrap3.png')
sprites.debris.greenCore1 = love.graphics.newImage('sprites/effects/debris/greenCore1.png')
sprites.debris.greenCore2 = love.graphics.newImage('sprites/effects/debris/greenCore2.png')
sprites.debris.greenCore3 = love.graphics.newImage('sprites/effects/debris/greenCore3.png')
sprites.debris.greenCore4 = love.graphics.newImage('sprites/effects/debris/greenCore4.png')

sprites.effects2 = {}
sprites.effects2.explosion = love.graphics.newImage('sprites/effects2/explosion.png')
sprites.effects2.magicExplosion = love.graphics.newImage('sprites/effects2/magicExplosion.png')
sprites.effects2.elecExplosion = love.graphics.newImage('sprites/effects2/elecExplosion.png')
sprites.effects2.spark = love.graphics.newImage('sprites/effects2/spark.png')
sprites.effects2.enemySpawn = love.graphics.newImage('sprites/effects2/enemySpawn.png')
sprites.effects2.poisonSmoke = love.graphics.newImage('sprites/effects2/poisonSmoke.png')
sprites.effects2.poisonGreen = love.graphics.newImage('sprites/effects2/poisonGreen.png')
sprites.effects2.poisonSmokeSmall = love.graphics.newImage('sprites/effects2/poisonSmokeSmall.png')
sprites.effects2.hyperBeam = love.graphics.newImage('sprites/effects2/hyper-beam.png')
sprites.effects2.spawnMagic = love.graphics.newImage('sprites/effects2/spawnMagic.png')
sprites.effects2.scorch = love.graphics.newImage('sprites/effects2/scorch.png')
sprites.effects2.flameAttack = love.graphics.newImage('sprites/effects2/flameAttack.png')
sprites.effects2.enemySpawn2a = love.graphics.newImage('sprites/effects2/enemySpawn2a.png')
sprites.effects2.enemySpawn2b = love.graphics.newImage('sprites/effects2/enemySpawn2b.png')
sprites.effects2.enemySpawn3 = love.graphics.newImage('sprites/effects2/enemySpawn3.png')
sprites.effects2.simpleSpawn = love.graphics.newImage('sprites/effects2/simpleSpawn.png')
sprites.effects2.attacks = {}
sprites.effects2.attacks.slice = love.graphics.newImage('sprites/effects2/attacks/slice.png')
sprites.effects2.attacks.sliceHot = love.graphics.newImage('sprites/effects2/attacks/sliceHot.png')
sprites.effects2.attacks.sliceBig = love.graphics.newImage('sprites/effects2/attacks/sliceBig.png')
sprites.effects2.attacks.sliceBigGreen = love.graphics.newImage('sprites/effects2/attacks/sliceBigGreen.png')
sprites.effects2.attacks.sliceBigHot = love.graphics.newImage('sprites/effects2/attacks/sliceBigHot.png')
sprites.effects2.attacks.stab = love.graphics.newImage('sprites/effects2/attacks/stab.png')
sprites.effects2.attacks.stabHot = love.graphics.newImage('sprites/effects2/attacks/stabHot.png')
sprites.effects2.attacks.stabBig = love.graphics.newImage('sprites/effects2/attacks/stabBig.png')
sprites.effects2.attacks.stabBigHot = love.graphics.newImage('sprites/effects2/attacks/stabBigHot.png')
sprites.effects2.attacks.shockBall = love.graphics.newImage('sprites/effects2/attacks/shockBall.png')
sprites.effects2.attacks.spikeVine = love.graphics.newImage('sprites/effects2/attacks/spikeVine.png')
sprites.effects2.attacks.windSlam = love.graphics.newImage('sprites/effects2/attacks/windSlam.png')
sprites.effects2.attacks.windSlamBig = love.graphics.newImage('sprites/effects2/attacks/windSlamBig.png')
sprites.effects2.attacks.greenBlast = love.graphics.newImage('sprites/effects2/attacks/greenBlast.png')
sprites.effects2.attacks.greyBlast = love.graphics.newImage('sprites/effects2/attacks/greyBlast.png')
sprites.effects2.attacks.elecSpiral = love.graphics.newImage('sprites/effects2/attacks/elecSpiral.png')
sprites.effects2.attacks.elecDisc = love.graphics.newImage('sprites/effects2/attacks/elecDisc.png')
sprites.effects2.attacks.bolt = love.graphics.newImage('sprites/effects2/attacks/bolt.png')
sprites.effects2.attacks.zap = love.graphics.newImage('sprites/effects2/attacks/zap.png')
sprites.effects2.attacks.fireballSm = love.graphics.newImage('sprites/effects2/attacks/fireballSm.png')
sprites.effects2.attacks.projSlashGreen = love.graphics.newImage('sprites/effects2/attacks/projSlashGreen2.png')
sprites.effects2.attacks.projSlashSimple = love.graphics.newImage('sprites/effects2/attacks/projSlashSimple.png')
sprites.effects2.attacks.projSlashSm = love.graphics.newImage('sprites/effects2/attacks/projSlashSm.png')

sprites.attacks = {}
sprites.attacks.smokeBomb = love.graphics.newImage('sprites/enemies/attacks/smokeBomb.png')
sprites.attacks.momFlower = love.graphics.newImage('sprites/enemies/attacks/momFlower.png')

sprites.chests = {}
sprites.chests.small = {}
sprites.chests.small.closed = love.graphics.newImage('sprites/environment/chests/smallClosed.png')
sprites.chests.small.open = love.graphics.newImage('sprites/environment/chests/smallOpen.png')
sprites.chests.big = {}
sprites.chests.big.closed = love.graphics.newImage('sprites/environment/chests/bigBlueClosed.png')
sprites.chests.big.open = love.graphics.newImage('sprites/environment/chests/bigBlueOpen.png')
sprites.environment = {}
sprites.environment.breakableRock = love.graphics.newImage('sprites/environment/breakableRock.png')
sprites.environment.breakableRockSm = love.graphics.newImage('sprites/environment/breakableRockSm.png')
sprites.environment.breakableWall = love.graphics.newImage('sprites/environment/breakableWall.png')
sprites.environment.scrapSm = love.graphics.newImage('sprites/environment/scrapSm.png')
sprites.environment.scrapBig = love.graphics.newImage('sprites/environment/scrapBig.png')
sprites.environment.lockedDoor = love.graphics.newImage('sprites/environment/lockedDoor.png')
sprites.environment.tree = love.graphics.newImage('sprites/environment/tree.png')
sprites.environment.tree2 = love.graphics.newImage('sprites/environment/tree2.png')
sprites.environment.wave = love.graphics.newImage('sprites/environment/wave.png')
sprites.environment.sink = love.graphics.newImage('sprites/environment/sink.png')
sprites.environment.vines = love.graphics.newImage('sprites/environment/vines.png')
sprites.environment.shrub = love.graphics.newImage('sprites/environment/shrub.png')
sprites.environment.cave = love.graphics.newImage('sprites/environment/cave.png')
sprites.environment.sunflower = love.graphics.newImage('sprites/environment/sunflower.png')
sprites.environment.dirt = love.graphics.newImage('sprites/environment/dirt.png')
sprites.environment.dirt2 = love.graphics.newImage('sprites/environment/dirt2.png')
sprites.environment.dirtDone = love.graphics.newImage('sprites/environment/dirtDone.png')
sprites.environment.gemStatue = love.graphics.newImage('sprites/environment/gem-statue.png')
sprites.environment.gemStatueEyes = love.graphics.newImage('sprites/environment/gem-statue-eyes.png')
sprites.environment.plants = {}
sprites.environment.plants.sprout1 = love.graphics.newImage('sprites/environment/plants/sprout1.png')
sprites.environment.plants.sprout2 = love.graphics.newImage('sprites/environment/plants/sprout2.png')
sprites.environment.plants.tallGrass1 = love.graphics.newImage('sprites/environment/plants/tallGrass1.png')
sprites.environment.plants.tallGrass2 = love.graphics.newImage('sprites/environment/plants/tallGrass2.png')
sprites.environment.plants.oldGrass = love.graphics.newImage('sprites/environment/plants/oldGrass.png')
sprites.environment.plants.climbVine = love.graphics.newImage('sprites/environment/plants/climbVine.png')
sprites.environment.trees = {}
sprites.environment.trees.tree1 = love.graphics.newImage('sprites/environment/trees/tree1.png')
sprites.environment.trees.pine1 = love.graphics.newImage('sprites/environment/trees/pine1.png')
sprites.environment.trees.blossom1 = love.graphics.newImage('sprites/environment/trees/blossom1.png')
sprites.environment.trees.fir1 = love.graphics.newImage('sprites/environment/trees/fir1.png')
sprites.environment.trees.big1 = love.graphics.newImage('sprites/environment/trees/big1.png')
sprites.environment.trees.pillar1 = love.graphics.newImage('sprites/environment/trees/pillar1.png')
sprites.environment.trees.banner = love.graphics.newImage('sprites/environment/trees/banner.png')
sprites.environment.trees.banner2 = love.graphics.newImage('sprites/environment/trees/banner2.png')
sprites.environment.trees.campfire = love.graphics.newImage('sprites/environment/trees/campfire.png')
sprites.environment.trees.sign1 = love.graphics.newImage('sprites/environment/trees/sign1.png')
sprites.environment.trees.streetlight = love.graphics.newImage('sprites/environment/trees/streetlight.png')
sprites.environment.trees.plug = love.graphics.newImage('sprites/environment/trees/plug.png')
sprites.environment.trees.stump = love.graphics.newImage('sprites/environment/trees/stump.png')
sprites.environment.trees.stumpLayer = love.graphics.newImage('sprites/environment/trees/stumpLayer.png')
sprites.environment.trees.orbDefault = love.graphics.newImage('sprites/environment/trees/orbDefault.png')
sprites.environment.trees.orbGreen = love.graphics.newImage('sprites/environment/trees/orbGreen.png')
sprites.environment.trees.kiln = love.graphics.newImage('sprites/environment/trees/kiln.png')
sprites.environment.trees.raft = love.graphics.newImage('sprites/environment/trees/raft.png')
sprites.environment.trees.ship = love.graphics.newImage('sprites/environment/trees/ship.png')
sprites.environment.trees.tableMap = love.graphics.newImage('sprites/environment/trees/tableMap.png')
sprites.environment.trees.gemPedestal = love.graphics.newImage('sprites/environment/trees/gem-pedestal.png')

sprites.environment.trees.standard = love.graphics.newImage('sprites/environment/trees/standard.png')
sprites.environment.trees.pine = love.graphics.newImage('sprites/environment/trees/pine.png')
sprites.environment.trees.blossom = love.graphics.newImage('sprites/environment/trees/blossom.png')
sprites.environment.trees.big = love.graphics.newImage('sprites/environment/trees/big.png')

sprites.environment.trees.appleOverlay = love.graphics.newImage('sprites/environment/trees/appleOverlay2.png')

sprites.environment.hazards = {}
sprites.environment.hazards.spikes = love.graphics.newImage('sprites/environment/hazards/spikes.png')
sprites.environment.hazards.vine = love.graphics.newImage('sprites/environment/hazards/vine.png')
sprites.environment.platforms = {}
sprites.environment.platforms.cloud = love.graphics.newImage('sprites/environment/platforms/cloudSm.png')
sprites.environment.platforms.cloudChargeOff = love.graphics.newImage('sprites/environment/platforms/cloudSmInactive.png')
sprites.environment.platforms.cloudChargeOn = love.graphics.newImage('sprites/environment/platforms/cloudSmActive.png')
sprites.environment.platforms.cloudChargeCrashed = love.graphics.newImage('sprites/environment/platforms/cloudSmCrashed.png')

sprites.environment.weather = {}
sprites.environment.weather.leaf = love.graphics.newImage('sprites/environment/weather/leaf3.png')

sprites.enemies = {}
sprites.enemies.balloon = love.graphics.newImage('sprites/enemies/balloon.png')
sprites.enemies.skullBat = love.graphics.newImage('sprites/enemies/skullBat.png')
sprites.enemies.golem = love.graphics.newImage('sprites/enemies/golem.png')
sprites.enemies.cloudSpirit = love.graphics.newImage('sprites/enemies/cloudSpirit.png')
sprites.enemies.dummy = love.graphics.newImage('sprites/enemies/dummy.png')
sprites.enemies.slimeRed = love.graphics.newImage('sprites/enemies/slimeRed.png')
sprites.enemies.skeleton = love.graphics.newImage('sprites/enemies/skeleton.png')
sprites.enemies.eyeBody = love.graphics.newImage('sprites/enemies/eyeBody.png')
sprites.enemies.eyeBall = love.graphics.newImage('sprites/enemies/eyeBall.png')
sprites.enemies.eyeIris = love.graphics.newImage('sprites/enemies/eyeIris.png')
sprites.enemies.eyeIrisSmall = love.graphics.newImage('sprites/enemies/eyeIrisSmall.png')
sprites.enemies.carnivorock = love.graphics.newImage('sprites/enemies/carnivorock.png')
sprites.enemies.hornetSoldier = love.graphics.newImage('sprites/enemies/hornetSoldier.png')
sprites.enemies.hornetWings = love.graphics.newImage('sprites/enemies/hornetWings.png')
sprites.enemies.hornetWorker = love.graphics.newImage('sprites/enemies/hornetWorker.png')
sprites.enemies.jelly = love.graphics.newImage('sprites/enemies/jelly.png')
sprites.enemies.jellyActive = love.graphics.newImage('sprites/enemies/jellyActive.png')
sprites.enemies.sentry = love.graphics.newImage('sprites/enemies/sentry.png')
sprites.enemies.kotengu = love.graphics.newImage('sprites/enemies/kotengu.png')
sprites.enemies.puff = love.graphics.newImage('sprites/enemies/puff.png')

sprites.enemies.eyeris = love.graphics.newImage('sprites/enemies/bosses/eyeris.png')
sprites.enemies.eyerisEye = love.graphics.newImage('sprites/enemies/bosses/eyeris-eye.png')
sprites.enemies.cloudBoss = love.graphics.newImage('sprites/enemies/bosses/cloudBoss.png')
sprites.enemies.daitengu = love.graphics.newImage('sprites/enemies/bosses/daitengu.png')
sprites.enemies.mom = love.graphics.newImage('sprites/enemies/bosses/mom.png')
sprites.enemies.momIris = love.graphics.newImage('sprites/enemies/bosses/momIris.png')

sprites.props = {}
sprites.props.pot = love.graphics.newImage('sprites/props/pot.png')
sprites.props.box = love.graphics.newImage('sprites/props/box.png')
sprites.props.box2 = love.graphics.newImage('sprites/props/box2.png')
sprites.props.logs = love.graphics.newImage('sprites/props/logs.png')
sprites.props.shelf = love.graphics.newImage('sprites/props/shelf.png')
sprites.props.shelf2 = love.graphics.newImage('sprites/props/shelf2.png')
sprites.props.shelf3 = love.graphics.newImage('sprites/props/shelf3.png')
sprites.props.bed = love.graphics.newImage('sprites/props/bed.png')
sprites.props.bed2 = love.graphics.newImage('sprites/props/bed2.png')
sprites.props.bed3 = love.graphics.newImage('sprites/props/bed3.png')
sprites.props.bed4 = love.graphics.newImage('sprites/props/bed4.png')
sprites.props.bed5 = love.graphics.newImage('sprites/props/bed5.png')
sprites.props.bed6 = love.graphics.newImage('sprites/props/bed6.png')
sprites.props.chair = love.graphics.newImage('sprites/props/chair.png')
sprites.props.barrel = love.graphics.newImage('sprites/props/barrel.png')
sprites.props.stool = love.graphics.newImage('sprites/props/stool.png')

sprites.items = {}
sprites.items.sword = love.graphics.newImage('sprites/weapons/sword.png')
sprites.items.sword2 = love.graphics.newImage('sprites/weapons/sword.png')
sprites.items.scepter = love.graphics.newImage('sprites/items/scepter.png')
sprites.items.star = love.graphics.newImage('sprites/items/star/star.png')
sprites.items.arrow = love.graphics.newImage('sprites/items/bow/arrow.png')
sprites.items.arrowBuried = love.graphics.newImage('sprites/items/arrowBuried.png')
sprites.items.bombArrow = love.graphics.newImage('sprites/items/bomb-arrow.png')
sprites.items.bow1 = love.graphics.newImage('sprites/items/bow/bow.png')
sprites.items.bow2 = love.graphics.newImage('sprites/items/bow/bow.png')
sprites.items.bowIcon = love.graphics.newImage('sprites/items/bow/bow-icon.png')
sprites.items.bomb = love.graphics.newImage('sprites/items/bomb.png')
sprites.items.bomb2 = love.graphics.newImage('sprites/items/bomb2.png')
sprites.items.electricBomb = love.graphics.newImage('sprites/items/elecBomb.png')
sprites.items.bombSheet = love.graphics.newImage('sprites/items/bombSheet.png')
sprites.items.boomerang = love.graphics.newImage('sprites/items/boomerang.png')
sprites.items.fire = love.graphics.newImage('sprites/items/fire-icon.png')
sprites.items.grapple = love.graphics.newImage('sprites/items/grapple.png')
sprites.items.grappleArmed = love.graphics.newImage('sprites/items/grapple-armed.png')
sprites.items.grappleChain = love.graphics.newImage('sprites/items/grapple-chain.png')
sprites.items.grappleHandle = love.graphics.newImage('sprites/items/grapple-handle.png')
sprites.items.grappleHead = love.graphics.newImage('sprites/items/grapple-head.png')
sprites.items.key = love.graphics.newImage('sprites/items/key.png')
sprites.items.coin = love.graphics.newImage('sprites/items/coin.png')
sprites.items.coin1 = love.graphics.newImage('sprites/items/coin1Sheet.png')
sprites.items.coin2 = love.graphics.newImage('sprites/items/coin2Sheet.png')
sprites.items.coin3 = love.graphics.newImage('sprites/items/coin3Sheet.png')
sprites.items.heart = love.graphics.newImage('sprites/items/heart.png')
sprites.items.container = love.graphics.newImage('sprites/items/container.png')
sprites.items.quiver = love.graphics.newImage('sprites/items/quiver.png')
sprites.items.lootShadow = love.graphics.newImage('sprites/items/lootShadow.png')
sprites.items.lootShadow2 = love.graphics.newImage('sprites/items/lootShadow2.png')
sprites.items.icons = {}
sprites.items.icons.heart = love.graphics.newImage('sprites/ui/icons/heart2.png')
sprites.items.icons.items = {}
sprites.items.icons.items.sword = love.graphics.newImage('sprites/ui/icons/items/swordIcon.png')
sprites.items.icons.items.bow = love.graphics.newImage('sprites/ui/icons/items/bowIcon.png')
sprites.items.icons.items.star = love.graphics.newImage('sprites/ui/icons/items/starIcon.png')
sprites.items.icons.spells = {}
sprites.items.icons.spells.lightning = love.graphics.newImage('sprites/ui/icons/spells/lightning.png')
sprites.items.icons.spells.fire = love.graphics.newImage('sprites/ui/icons/spells/fire.png')
sprites.items.icons.spells.ice = love.graphics.newImage('sprites/ui/icons/spells/ice.png')
sprites.items.icons.tools = {}
sprites.items.icons.tools.swim = love.graphics.newImage('sprites/ui/icons/tools/flamingo.png')
sprites.items.icons.lantern = love.graphics.newImage('sprites/ui/icons/items/lantern.png')

sprites.items.icons.coinAnim = love.graphics.newImage('sprites/items/icons/coinAnim.png')
sprites.items.icons.lanternAnim = love.graphics.newImage('sprites/items/icons/lanternAnim.png')
sprites.items.icons.gauntlets = love.graphics.newImage('sprites/items/icons/gauntlets.png')
sprites.items.icons.lightning = love.graphics.newImage('sprites/items/icons/lightning5.png')
sprites.items.icons.ringVit = love.graphics.newImage('sprites/items/icons/ringVit.png')
sprites.items.icons.moonstone = love.graphics.newImage('sprites/items/icons/moonstone.png')
sprites.items.icons.map = love.graphics.newImage('sprites/items/icons/map.png')
sprites.items.icons.multi = love.graphics.newImage('sprites/items/icons/multi.png')
sprites.items.icons.shovel = love.graphics.newImage('sprites/items/icons/shovel.png')
sprites.items.icons.ring = love.graphics.newImage('sprites/items/icons/gems/ring/ring.png')
sprites.items.icons.necklace = love.graphics.newImage('sprites/items/icons/gems/necklace/necklace.png')

sprites.items.icons.dye_default = love.graphics.newImage('sprites/items/icons/dyes/dyeDefault.png')
sprites.items.icons.dye_red = love.graphics.newImage('sprites/items/icons/dyes/dyeRed.png')
sprites.items.icons.dye_orange = love.graphics.newImage('sprites/items/icons/dyes/dyeOrange.png')
sprites.items.icons.dye_yellow = love.graphics.newImage('sprites/items/icons/dyes/dyeYellow.png')
sprites.items.icons.dye_green = love.graphics.newImage('sprites/items/icons/dyes/dyeGreen.png')
sprites.items.icons.dye_blue = love.graphics.newImage('sprites/items/icons/dyes/dyeBlue.png')
sprites.items.icons.dye_purple = love.graphics.newImage('sprites/items/icons/dyes/dyePurple.png')
sprites.items.icons.dye_white = love.graphics.newImage('sprites/items/icons/dyes/dyeWhite.png')

sprites.items.icons.gems = {}
sprites.items.icons.gems.ruby = love.graphics.newImage('sprites/items/icons/gems/ruby.png')
sprites.items.icons.gems.emerald = love.graphics.newImage('sprites/items/icons/gems/emerald.png')
sprites.items.icons.gems.amethyst = love.graphics.newImage('sprites/items/icons/gems/amethyst.png')
sprites.items.icons.gems.garnet = love.graphics.newImage('sprites/items/icons/gems/garnet.png')
sprites.items.icons.gems.topaz = love.graphics.newImage('sprites/items/icons/gems/topaz.png')
sprites.items.icons.gems.sapphire = love.graphics.newImage('sprites/items/icons/gems/sapphire.png')

sprites.items.icons.ring_ruby = love.graphics.newImage('sprites/items/icons/gems/ring/ring_ruby.png')
sprites.items.icons.ring_emerald = love.graphics.newImage('sprites/items/icons/gems/ring/ring_emerald.png')
sprites.items.icons.ring_amethyst = love.graphics.newImage('sprites/items/icons/gems/ring/ring_amethyst.png')

sprites.items.icons.necklace_ruby = love.graphics.newImage('sprites/items/icons/gems/necklace/necklace_ruby.png')
sprites.items.icons.necklace_emerald = love.graphics.newImage('sprites/items/icons/gems/necklace/necklace_emerald.png')
sprites.items.icons.necklace_amethyst = love.graphics.newImage('sprites/items/icons/gems/necklace/necklace_amethyst.png')

sprites.items.resources = {}
sprites.items.resources.battery1 = love.graphics.newImage('sprites/items/resources/battery1.png')
sprites.items.resources.bone1 = love.graphics.newImage('sprites/items/resources/bone1.png')
sprites.items.resources.bone2 = love.graphics.newImage('sprites/items/resources/bone2.png')
sprites.items.resources.bone3 = love.graphics.newImage('sprites/items/resources/bone3.png')
sprites.items.resources.fish1 = love.graphics.newImage('sprites/items/resources/fish1.png')
sprites.items.resources.gold1 = love.graphics.newImage('sprites/items/resources/gold1.png')
sprites.items.resources.gold2 = love.graphics.newImage('sprites/items/resources/gold2.png')
sprites.items.resources.gold3 = love.graphics.newImage('sprites/items/resources/gold3.png')
sprites.items.resources.seed1 = love.graphics.newImage('sprites/items/resources/seed1.png')
sprites.items.resources.seed2 = love.graphics.newImage('sprites/items/resources/seed2.png')
sprites.items.resources.ore1 = love.graphics.newImage('sprites/items/resources/ore1.png')
sprites.items.resources.diamond1 = love.graphics.newImage('sprites/items/resources/diamond1.png')

sprites.items.icons.smallGems = {}
sprites.items.icons.smallGems.diamond = love.graphics.newImage('sprites/items/icons/smallGems/diamond.png')
sprites.items.icons.smallGems.ruby = love.graphics.newImage('sprites/items/icons/smallGems/ruby.png')
sprites.items.icons.smallGems.garnet = love.graphics.newImage('sprites/items/icons/smallGems/garnet.png')
sprites.items.icons.smallGems.topaz = love.graphics.newImage('sprites/items/icons/smallGems/topaz.png')
sprites.items.icons.smallGems.emerald = love.graphics.newImage('sprites/items/icons/smallGems/emerald.png')
sprites.items.icons.smallGems.sapphire = love.graphics.newImage('sprites/items/icons/smallGems/sapphire.png')
sprites.items.icons.smallGems.amethyst = love.graphics.newImage('sprites/items/icons/smallGems/amethyst.png')

sprites.gui = {}
sprites.gui.keyboardButton = love.graphics.newImage('sprites/ui/icons/gui/keyboard-button.png')
sprites.gui.mouseLeft = love.graphics.newImage('sprites/ui/icons/gui/mouse-left.png')
sprites.gui.mouseRight = love.graphics.newImage('sprites/ui/icons/gui/mouse-right.png')
sprites.hud = {}
sprites.hud.heart = love.graphics.newImage('sprites/ui/hud/heart.png')
sprites.hud.heartSmall = love.graphics.newImage('sprites/ui/hud/heartSmall.png')
sprites.hud.armor = love.graphics.newImage('sprites/ui/hud/armor.png')
sprites.hud.ammoPanel = love.graphics.newImage('sprites/ui/hud/ammoPanel.png')

sprites.hud.moonPanel = love.graphics.newImage('sprites/ui/hud/moonPanel/moonPanel.png')
sprites.hud.moonQuarter1 = love.graphics.newImage('sprites/ui/hud/moonPanel/moonQuarter1.png')
sprites.hud.moonQuarter3 = love.graphics.newImage('sprites/ui/hud/moonPanel/moonQuarter3.png')
sprites.hud.moonHalf = love.graphics.newImage('sprites/ui/hud/moonPanel/moonHalf.png')
sprites.hud.moonEmpty = love.graphics.newImage('sprites/ui/hud/moonPanel/moonEmpty.png')

sprites.hud.moonPanelG = love.graphics.newImage('sprites/ui/hud/moonPanel/moonPanelG.png')
sprites.hud.moonQuarter1G = love.graphics.newImage('sprites/ui/hud/moonPanel/moonQuarter1G.png')
sprites.hud.moonQuarter1R = love.graphics.newImage('sprites/ui/hud/moonPanel/moonQuarter1R.png')
sprites.hud.moonQuarter3G = love.graphics.newImage('sprites/ui/hud/moonPanel/moonQuarter3G.png')
sprites.hud.moonHalfG = love.graphics.newImage('sprites/ui/hud/moonPanel/moonHalfG.png')
sprites.hud.moonEmptyG = love.graphics.newImage('sprites/ui/hud/moonPanel/moonEmptyG.png')

sprites.hud.bossBar = love.graphics.newImage('sprites/ui/hud/bossBar.png')
sprites.hud.ammo = {}
sprites.hud.ammo.fire = love.graphics.newImage('sprites/ui/hud/ammo/fire.png')
sprites.hud.ammo.lightning = love.graphics.newImage('sprites/ui/hud/ammo/lightning.png')

sprites.hud.mana = {}
sprites.hud.mana.empty = love.graphics.newImage('sprites/ui/hud/mana/manabarE.png')
sprites.hud.mana.full = love.graphics.newImage('sprites/ui/hud/mana/manabarF.png')
sprites.hud.mana.back = love.graphics.newImage('sprites/ui/hud/mana/manabarBack.png')
sprites.hud.mana.frame = love.graphics.newImage('sprites/ui/hud/mana/manabarFrame.png')

sprites.pause = {}
sprites.pause.vertItems = love.graphics.newImage('sprites/ui/pause/vertItems.png')
sprites.pause.vertDyes = love.graphics.newImage('sprites/ui/pause/vertDyes.png')
sprites.pause.vertBlank = love.graphics.newImage('sprites/ui/pause/vertBlank.png')
sprites.pause.itemPanel = love.graphics.newImage('sprites/ui/pause/itemPanel.png')
sprites.pause.itemPanelHover = love.graphics.newImage('sprites/ui/pause/itemPanelHover.png')
sprites.pause.itemPanelActive = love.graphics.newImage('sprites/ui/pause/itemPanelActive.png')
sprites.pause.itemPanelActiveHover = love.graphics.newImage('sprites/ui/pause/itemPanelActiveHover.png')
sprites.pause.arrow = love.graphics.newImage('sprites/ui/pause/arrow.png')
sprites.pause.arrowHover = love.graphics.newImage('sprites/ui/pause/arrowHover.png')
sprites.pause.dotOn = love.graphics.newImage('sprites/ui/pause/dotOn.png')
sprites.pause.dotOff = love.graphics.newImage('sprites/ui/pause/dotOff.png')

sprites.settings = {}
sprites.settings.icon = love.graphics.newImage('sprites/ui/icons/settingsIcon.png')
sprites.settings.checkmark = love.graphics.newImage('sprites/ui/icons/checkMark.png')
sprites.settings.smallWrench = love.graphics.newImage('sprites/ui/icons/smallWrench.png')
sprites.settings.add = love.graphics.newImage('sprites/ui/icons/add.png')
sprites.settings.subtract = love.graphics.newImage('sprites/ui/icons/subtract.png')
sprites.settings.volumeLow = love.graphics.newImage('sprites/ui/icons/volumeLow.png')
sprites.settings.volumeHigh = love.graphics.newImage('sprites/ui/icons/volumeHigh.png')
sprites.settings.back = love.graphics.newImage('sprites/ui/icons/back.png')
sprites.settings.panel = love.graphics.newImage('sprites/ui/settings/settingsPanel.png')
sprites.settings.smallButton = love.graphics.newImage('sprites/ui/settings/smallButton.png')
sprites.settings.smallButtonHover = love.graphics.newImage('sprites/ui/settings/smallButtonHover.png')
sprites.settings.smallestButton = love.graphics.newImage('sprites/ui/settings/smallestButton.png')
sprites.settings.smallestButtonHover = love.graphics.newImage('sprites/ui/settings/smallestButtonHover.png')
sprites.settings.bindButton = love.graphics.newImage('sprites/ui/settings/bindButton.png')
sprites.settings.bindButtonHover = love.graphics.newImage('sprites/ui/settings/bindButtonHover.png')
sprites.settings.wideButton = love.graphics.newImage('sprites/ui/settings/wideButton.png')
sprites.settings.wideButtonHover = love.graphics.newImage('sprites/ui/settings/wideButtonHover.png')
sprites.settings.widerButton = love.graphics.newImage('sprites/ui/settings/widerButton.png')
sprites.settings.widerButtonHover = love.graphics.newImage('sprites/ui/settings/widerButtonHover.png')
sprites.settings.widerButtonActive = love.graphics.newImage('sprites/ui/settings/widerButtonActive.png')
sprites.settings.widerButtonActiveHover = love.graphics.newImage('sprites/ui/settings/widerButtonActiveHover.png')
sprites.settings.soundBar = love.graphics.newImage('sprites/ui/settings/soundBar.png')
sprites.keybinds = {}
sprites.keybinds.panel = love.graphics.newImage('sprites/ui/keybinds/panel.png')
sprites.keybinds.panelHover = love.graphics.newImage('sprites/ui/keybinds/panelHover.png')
sprites.keybinds.newPanel = love.graphics.newImage('sprites/ui/keybinds/newPanel.png')
sprites.keybinds.newPanelHover = love.graphics.newImage('sprites/ui/keybinds/newPanelHover.png')
sprites.ui = {}
sprites.ui.logo = love.graphics.newImage('sprites/ui/logo.png')
sprites.ui.map = love.graphics.newImage('sprites/ui/map/map.png')
sprites.ui.room = love.graphics.newImage('sprites/ui/map/room.png')
sprites.ui.hall = love.graphics.newImage('sprites/ui/map/hall.png')
sprites.ui.playerIcon = love.graphics.newImage('sprites/ui/map/playerIcon.png')
sprites.ui.messageBack = love.graphics.newImage('sprites/ui/messageBack.png')
sprites.ui.infoPanel = love.graphics.newImage('sprites/ui/infoPanel.png')
sprites.ui.dialogueBack = love.graphics.newImage('sprites/ui/dialogueBack3.png')
sprites.ui.dialogueFrame = love.graphics.newImage('sprites/ui/dialogueFrame3.png')
sprites.ui.talk = love.graphics.newImage('sprites/ui/talk.png')
sprites.ui.downArrow = love.graphics.newImage('sprites/ui/downArrow.png')
sprites.ui.exclamation = love.graphics.newImage('sprites/ui/exclamation.png')
sprites.ui.infoCursor = love.graphics.newImage('sprites/ui/icons/cursor.png')
sprites.ui.answerBack = love.graphics.newImage('sprites/ui/answerBack.png')
sprites.ui.answerFrame = love.graphics.newImage('sprites/ui/answerFrame.png')
sprites.ui.answerFrameNew = love.graphics.newImage('sprites/ui/answerFrameNew.png')
sprites.ui.answerFrameNewHover = love.graphics.newImage('sprites/ui/answerFrameNewHover.png')
sprites.ui.answerFrameNewSmall = love.graphics.newImage('sprites/ui/answerFrameNewSmall.png')
sprites.ui.answerFrameNewHoverSmall = love.graphics.newImage('sprites/ui/answerFrameNewHoverSmall.png')
sprites.ui.fullPaperMap = love.graphics.newImage('maps/paperMap/fullPaperMap.png')
sprites.ui.gemBox = love.graphics.newImage('sprites/ui/gemBox.png')
sprites.ui.gemBoxFrame1 = love.graphics.newImage('sprites/ui/gemBoxFrame1.png')
sprites.ui.gemBoxFrame2 = love.graphics.newImage('sprites/ui/gemBoxFrame2.png')
sprites.ui.text = {}
sprites.ui.text.continue = love.graphics.newImage('sprites/ui/text/continue.png')

local base = 'sprites/ui/controls/'
sprites.ui.controls = {}
sprites.ui.controls.leftStickD = love.graphics.newImage(base .. 'leftStickD.png')
sprites.ui.controls.leftStickU = love.graphics.newImage(base .. 'leftStickU.png')
sprites.ui.controls.leftStickL = love.graphics.newImage(base .. 'leftStickL.png')
sprites.ui.controls.leftStickR = love.graphics.newImage(base .. 'leftStickR.png')
sprites.ui.controls.rightStickD = love.graphics.newImage(base .. 'rightStickD.png')
sprites.ui.controls.rightStickU = love.graphics.newImage(base .. 'rightStickU.png')
sprites.ui.controls.rightStickL = love.graphics.newImage(base .. 'rightStickL.png')
sprites.ui.controls.rightStickR = love.graphics.newImage(base .. 'rightStickR.png')
sprites.ui.controls.mouse1 = love.graphics.newImage(base .. 'mouse1.png')
sprites.ui.controls.mouse2 = love.graphics.newImage(base .. 'mouse2.png')
sprites.ui.controls.mouse3 = love.graphics.newImage(base .. 'mouse3.png')
sprites.ui.controls.triggerL = love.graphics.newImage(base .. 'triggerL.png')
sprites.ui.controls.triggerR = love.graphics.newImage(base .. 'triggerR.png')

base = 'sprites/ui/controls/keys/'
sprites.ui.controls.keys = {}
sprites.ui.controls.keys['0'] = love.graphics.newImage(base .. '0.png')
sprites.ui.controls.keys['1'] = love.graphics.newImage(base .. '1.png')
sprites.ui.controls.keys['2'] = love.graphics.newImage(base .. '2.png')
sprites.ui.controls.keys['3'] = love.graphics.newImage(base .. '3.png')
sprites.ui.controls.keys['4'] = love.graphics.newImage(base .. '4.png')
sprites.ui.controls.keys['5'] = love.graphics.newImage(base .. '5.png')
sprites.ui.controls.keys['6'] = love.graphics.newImage(base .. '6.png')
sprites.ui.controls.keys['7'] = love.graphics.newImage(base .. '7.png')
sprites.ui.controls.keys['8'] = love.graphics.newImage(base .. '8.png')
sprites.ui.controls.keys['9'] = love.graphics.newImage(base .. '9.png')
sprites.ui.controls.keys.a = love.graphics.newImage(base .. 'a.png')
sprites.ui.controls.keys.b = love.graphics.newImage(base .. 'b.png')
sprites.ui.controls.keys.c = love.graphics.newImage(base .. 'c.png')
sprites.ui.controls.keys.d = love.graphics.newImage(base .. 'd.png')
sprites.ui.controls.keys.e = love.graphics.newImage(base .. 'e.png')
sprites.ui.controls.keys.f = love.graphics.newImage(base .. 'f.png')
sprites.ui.controls.keys.g = love.graphics.newImage(base .. 'g.png')
sprites.ui.controls.keys.h = love.graphics.newImage(base .. 'h.png')
sprites.ui.controls.keys.i = love.graphics.newImage(base .. 'i.png')
sprites.ui.controls.keys.j = love.graphics.newImage(base .. 'j.png')
sprites.ui.controls.keys.k = love.graphics.newImage(base .. 'k.png')
sprites.ui.controls.keys.l = love.graphics.newImage(base .. 'l.png')
sprites.ui.controls.keys.m = love.graphics.newImage(base .. 'm.png')
sprites.ui.controls.keys.n = love.graphics.newImage(base .. 'n.png')
sprites.ui.controls.keys.o = love.graphics.newImage(base .. 'o.png')
sprites.ui.controls.keys.p = love.graphics.newImage(base .. 'p.png')
sprites.ui.controls.keys.q = love.graphics.newImage(base .. 'q.png')
sprites.ui.controls.keys.r = love.graphics.newImage(base .. 'r.png')
sprites.ui.controls.keys.s = love.graphics.newImage(base .. 's.png')
sprites.ui.controls.keys.t = love.graphics.newImage(base .. 't.png')
sprites.ui.controls.keys.u = love.graphics.newImage(base .. 'u.png')
sprites.ui.controls.keys.v = love.graphics.newImage(base .. 'v.png')
sprites.ui.controls.keys.w = love.graphics.newImage(base .. 'w.png')
sprites.ui.controls.keys.x = love.graphics.newImage(base .. 'x.png')
sprites.ui.controls.keys.y = love.graphics.newImage(base .. 'y.png')
sprites.ui.controls.keys.z = love.graphics.newImage(base .. 'z.png')
sprites.ui.controls.keys.alt = love.graphics.newImage(base .. 'alt.png')
sprites.ui.controls.keys.ctrl = love.graphics.newImage(base .. 'ctrl.png')
sprites.ui.controls.keys.shift = love.graphics.newImage(base .. 'shift.png')
sprites.ui.controls.keys.space = love.graphics.newImage(base .. 'space.png')
sprites.ui.controls.keys.tab = love.graphics.newImage(base .. 'tab.png')
sprites.ui.controls.keys["return"] = love.graphics.newImage(base .. 'return.png')
sprites.ui.controls.keys.backspace = love.graphics.newImage(base .. 'backspace.png')
sprites.ui.controls.keys.delete = love.graphics.newImage(base .. 'delete.png')
sprites.ui.controls.keys.escape = love.graphics.newImage(base .. 'escape.png')
sprites.ui.controls.keys.up = love.graphics.newImage(base .. 'up.png')
sprites.ui.controls.keys.down = love.graphics.newImage(base .. 'down.png')
sprites.ui.controls.keys.left = love.graphics.newImage(base .. 'left.png')
sprites.ui.controls.keys.right = love.graphics.newImage(base .. 'right.png')

base = 'sprites/ui/controls/buttons/'
sprites.ui.controls.buttons = {}
sprites.ui.controls.buttons.a = love.graphics.newImage(base .. 'a.png')
sprites.ui.controls.buttons.b = love.graphics.newImage(base .. 'b.png')
sprites.ui.controls.buttons.x = love.graphics.newImage(base .. 'x.png')
sprites.ui.controls.buttons.y = love.graphics.newImage(base .. 'y.png')
sprites.ui.controls.buttons.dpdown = love.graphics.newImage(base .. 'dpdown.png')
sprites.ui.controls.buttons.dpleft = love.graphics.newImage(base .. 'dpleft.png')
sprites.ui.controls.buttons.dpright = love.graphics.newImage(base .. 'dpright.png')
sprites.ui.controls.buttons.dpup = love.graphics.newImage(base .. 'dpup.png')
sprites.ui.controls.buttons.leftshoulder = love.graphics.newImage(base .. 'leftshoulder.png')
sprites.ui.controls.buttons.rightshoulder = love.graphics.newImage(base .. 'rightshoulder.png')
sprites.ui.controls.buttons.start = love.graphics.newImage(base .. 'start.png')
sprites.ui.controls.buttons.back = love.graphics.newImage(base .. 'back.png')
sprites.ui.controls.buttons.psO = love.graphics.newImage(base .. 'psO.png')
sprites.ui.controls.buttons.psX = love.graphics.newImage(base .. 'psX.png')
sprites.ui.controls.buttons.psSq = love.graphics.newImage(base .. 'psSq.png')
sprites.ui.controls.buttons.psTr = love.graphics.newImage(base .. 'psTr.png')

sprites.ui.mainMenu = {}
sprites.ui.mainMenu.file = love.graphics.newImage('sprites/ui/mainMenu/file.png')

sprites.ui.menu = {}
sprites.ui.menu.logo = love.graphics.newImage('sprites/ui/menu/logo.png')
sprites.ui.menu.castle = love.graphics.newImage('sprites/ui/menu/castle.png')
sprites.ui.menu.moon = love.graphics.newImage('sprites/ui/menu/moon.png')

sprites.ui.buttons = {}
sprites.ui.buttons.scheme = love.graphics.newImage('sprites/ui/buttons/scheme.png')
sprites.ui.buttons.schemeActive = love.graphics.newImage('sprites/ui/buttons/schemeActive.png')
sprites.ui.buttons.main = love.graphics.newImage('sprites/ui/buttons/main.png')
sprites.ui.buttons.back = love.graphics.newImage('sprites/ui/buttons/back.png')
sprites.ui.buttons.mode = love.graphics.newImage('sprites/ui/buttons/mode.png')
sprites.ui.buttons.modeActive = love.graphics.newImage('sprites/ui/buttons/modeActive.png')
sprites.ui.buttons.start = love.graphics.newImage('sprites/ui/buttons/start.png')
sprites.ui.buttons.file = love.graphics.newImage('sprites/ui/buttons/file.png')
sprites.ui.buttons.checkbox = love.graphics.newImage('sprites/ui/buttons/checkbox.png')

sprites.ui.icons = {}
sprites.ui.icons.keyboard = love.graphics.newImage('sprites/ui/icons/keyboard.png')
sprites.ui.icons.controller = love.graphics.newImage('sprites/ui/icons/controller.png')
sprites.ui.icons.keyboardMouse = love.graphics.newImage('sprites/ui/icons/keyboardMouse.png')
sprites.ui.icons.star = love.graphics.newImage('sprites/ui/icons/star.png')
sprites.ui.icons.sideCursor = love.graphics.newImage('sprites/ui/icons/sideCursor.png')
sprites.ui.icons.sideArrow = love.graphics.newImage('sprites/ui/icons/sideArrow.png')
sprites.ui.icons.dot = love.graphics.newImage('sprites/ui/icons/dot.png')
sprites.ui.icons.x = love.graphics.newImage('sprites/ui/icons/x.png')

sprites.elevators = {}
sprites.elevators.elevator = love.graphics.newImage('sprites/environment/elevators/elevator.png')
sprites.elevators.elevatorActive = love.graphics.newImage('sprites/environment/elevators/elevatorActive.png')
sprites.elevators.green = love.graphics.newImage('sprites/environment/elevators/green.png')
sprites.elevators.greenActive = love.graphics.newImage('sprites/environment/elevators/greenActive.png')
sprites.elevators.leaves = love.graphics.newImage('sprites/environment/elevators/leaves.png')

sprites.rubble = {}
sprites.rubble.log = love.graphics.newImage('sprites/props/rubble/log.png')

sprites.rubble.shardL = love.graphics.newImage('sprites/props/rubble/shardL.png')
sprites.rubble.shardL2 = love.graphics.newImage('sprites/props/rubble/shardL2.png')
sprites.rubble.shardS = love.graphics.newImage('sprites/props/rubble/shardS.png')
sprites.rubble.shardS2 = love.graphics.newImage('sprites/props/rubble/shardS2.png')

sprites.rubble.wood = love.graphics.newImage('sprites/props/rubble/wood.png')
sprites.rubble.woodAlt = love.graphics.newImage('sprites/props/rubble/woodAlt.png')
sprites.rubble.woodDark = love.graphics.newImage('sprites/props/rubble/woodDark.png')
sprites.rubble.woodShade = love.graphics.newImage('sprites/props/rubble/woodShade.png')
sprites.rubble.woodChipped = love.graphics.newImage('sprites/props/rubble/woodChipped.png')
sprites.rubble.woodSmall = love.graphics.newImage('sprites/props/rubble/woodSmall.png')
sprites.rubble.woodSmallDark = love.graphics.newImage('sprites/props/rubble/woodSmallDark.png')
sprites.rubble.woodSmallShade = love.graphics.newImage('sprites/props/rubble/woodSmallShade.png')
sprites.rubble.woodSmallChipped = love.graphics.newImage('sprites/props/rubble/woodSmallChipped.png')

sprites.npc = {}
sprites.npc.shopkeeper = love.graphics.newImage('sprites/npc/shopkeeper.png')
sprites.npc.soldier = love.graphics.newImage('sprites/npc/soldier.png')
sprites.npc.soldier1 = love.graphics.newImage('sprites/npc/soldier1.png')
sprites.npc.soldier2 = love.graphics.newImage('sprites/npc/soldier2.png')
sprites.npc.soldier3 = love.graphics.newImage('sprites/npc/soldier3.png')
sprites.npc.blacksmith = love.graphics.newImage('sprites/npc/blacksmith.png')
sprites.npc.balloonGirl = love.graphics.newImage('sprites/npc/balloonGirl.png')
sprites.npc.balloonGame = love.graphics.newImage('sprites/npc/balloonGame.png')
sprites.npc.oldLady = love.graphics.newImage('sprites/npc/oldLady.png')
sprites.npc.sage = love.graphics.newImage('sprites/npc/sage.png')
sprites.npc.engineer = love.graphics.newImage('sprites/npc/engineer.png')
sprites.npc.kotengu = love.graphics.newImage('sprites/npc/kotengu.png')
sprites.npc.strategist = love.graphics.newImage('sprites/npc/strategist.png')
sprites.npc.wiseman = love.graphics.newImage('sprites/npc/wiseman.png')
sprites.npc.sailor = love.graphics.newImage('sprites/npc/sailor.png')
sprites.npc.farmer = love.graphics.newImage('sprites/npc/farmer.png')
sprites.weapons = {}
sprites.weapons.sword = love.graphics.newImage('sprites/weapons/sword.png')
sprites.weapons.swordGlow = love.graphics.newImage('sprites/weapons/sword-glow.png')
sprites.weapons.spear = love.graphics.newImage('sprites/weapons/spear.png')
sprites.weapons.spearH = love.graphics.newImage('sprites/weapons/spear-h.png')
sprites.weapons.spearGlow = love.graphics.newImage('sprites/weapons/spear-glow.png')
sprites.weapons.greatsword = love.graphics.newImage('sprites/weapons/greatsword.png')
sprites.weapons.greatswordH = love.graphics.newImage('sprites/weapons/greatsword-h.png')
sprites.weapons.greatswordGlow = love.graphics.newImage('sprites/weapons/greatsword-glow.png')
sprites.weapons.lightningRod0 = love.graphics.newImage('sprites/weapons/lightningRod0.png')
sprites.weapons.lightningRod1 = love.graphics.newImage('sprites/weapons/lightningRod1.png')
--sprites.weapons.lightningRod2 = love.graphics.newImage('sprites/weapons/lightningRod2.png')
sprites.weapons.lightningRod = love.graphics.newImage('sprites/weapons/lightningRod.png')
sprites.weapons.lightningRodGlow = love.graphics.newImage('sprites/weapons/lightningRod-glow.png')
sprites.weapons.lightningRodGround = love.graphics.newImage('sprites/weapons/lightningRod-ground.png')
sprites.weapons.greataxe = love.graphics.newImage('sprites/weapons/greataxe.png')
sprites.weapons.greataxeGlow = love.graphics.newImage('sprites/weapons/greataxe-glow.png')
sprites.weapons.torch = love.graphics.newImage('sprites/weapons/torch.png')
sprites.weapons.torchGlow = love.graphics.newImage('sprites/weapons/torch-glow.png')
sprites.weapons.boomerang = love.graphics.newImage('sprites/weapons/boomerang.png')
sprites.weapons.boomerangGlow = love.graphics.newImage('sprites/weapons/boomerang-glow.png')
sprites.weapons.sageStaff = love.graphics.newImage('sprites/weapons/sageStaff.png')
sprites.weapons.mace = love.graphics.newImage('sprites/weapons/mace.png')
sprites.weapons.leaf = love.graphics.newImage('sprites/weapons/leaf.png')
sprites.weapons.fan = love.graphics.newImage('sprites/weapons/fan.png')
sprites.weapons.glassAxe = love.graphics.newImage('sprites/weapons/glassAxe.png')
sprites.weapons.effects = {}
sprites.weapons.effects.fire = love.graphics.newImage('sprites/weapons/effects/fire.png')
sprites.weapons.effects.fireSmall = love.graphics.newImage('sprites/weapons/effects/fireSmall.png')
sprites.weapons.effects.fireTiny = love.graphics.newImage('sprites/weapons/effects/fireTiny.png')
sprites.weapons.npc = {}
sprites.weapons.npc.spear = love.graphics.newImage('sprites/weapons/npcSpear.png')
sprites.weapons.simple = {}
sprites.weapons.simple.forestRock = love.graphics.newImage('sprites/weapons/simple/forestRock.png')
sprites.weapons.simple.forestRockGlow = love.graphics.newImage('sprites/weapons/simple/forestRock-glow.png')
sprites.weapons.simple.pot = love.graphics.newImage('sprites/weapons/simple/pot.png')
sprites.weapons.simple.potGlow = love.graphics.newImage('sprites/weapons/simple/pot-glow.png')
sprites.weapons.simple.cherryBomb = love.graphics.newImage('sprites/weapons/simple/cherryBomb.png')
sprites.weapons.simple.cherryBombGlow = love.graphics.newImage('sprites/weapons/simple/cherryBomb-glow.png')
sprites.weapons.simple.battery = love.graphics.newImage('sprites/weapons/simple/battery.png')
sprites.weapons.simple.batteryGlow = love.graphics.newImage('sprites/weapons/simple/battery-glow.png')
sprites.bg = {}
sprites.bg.skyTitle = {}
sprites.bg.skyTitle[1] = love.graphics.newImage('sprites/backgrounds/skyTitle/layer1.png')
sprites.bg.skyTitle[2] = love.graphics.newImage('sprites/backgrounds/skyTitle/layer2.png')
sprites.bg.skyTitle[3] = love.graphics.newImage('sprites/backgrounds/skyTitle/layer3.png')
sprites.bg.skyTitle[4] = love.graphics.newImage('sprites/backgrounds/skyTitle/layer4.png')
sprites.bg.skyTitle[5] = love.graphics.newImage('sprites/backgrounds/skyTitle/layer5.png')
sprites.bg.skyTitle[6] = love.graphics.newImage('sprites/backgrounds/skyTitle/layer6.png')
sprites.bg.skyTitle[7] = love.graphics.newImage('sprites/backgrounds/skyTitle/layer7.png')
sprites.bg.skyTitle[8] = love.graphics.newImage('sprites/backgrounds/skyTitle/layer8.png')
sprites.bg.skyTitle[9] = love.graphics.newImage('sprites/backgrounds/skyTitle/layer9.png')
sprites.bg.skyTitle[10] = love.graphics.newImage('sprites/backgrounds/skyTitle/layer10.png')
sprites.bg.void = {}
sprites.bg.void[1] = love.graphics.newImage('sprites/backgrounds/void/layer1.png')
sprites.bg.eyeris = {}
sprites.bg.eyeris[1] = love.graphics.newImage('sprites/backgrounds/eyeris/layer1.png')
sprites.bg.eyeris[2] = love.graphics.newImage('sprites/backgrounds/eyeris/layer2.png')
sprites.bg.cloudDungeon = {}
sprites.bg.cloudDungeon[1] = love.graphics.newImage('sprites/backgrounds/cloudDungeon/layer1.png')
sprites.bg.cloudDungeon[2] = love.graphics.newImage('sprites/backgrounds/cloudDungeon/layer2.png')
sprites.bg.cloudBoss1 = {}
sprites.bg.cloudBoss1[1] = love.graphics.newImage('sprites/backgrounds/cloudBoss/layer1.png')
sprites.bg.cloudBoss1[2] = love.graphics.newImage('sprites/backgrounds/cloudBoss/layer2.png')
sprites.bg.cloudBoss2 = {}
sprites.bg.cloudBoss2[1] = love.graphics.newImage('sprites/backgrounds/cloudBoss/layer1.png')
sprites.bg.cloudBoss2[2] = love.graphics.newImage('sprites/backgrounds/cloudBoss/layer2.png')
sprites.bg.cloudDungeon.island = love.graphics.newImage('sprites/backgrounds/cloudDungeon/islandBack3.png')
sprites.bg.cloudDungeon.island4 = love.graphics.newImage('sprites/backgrounds/cloudDungeon/islandBack4.png')
sprites.bg.cloudDungeon.island5 = love.graphics.newImage('sprites/backgrounds/cloudDungeon/islandBack5.png')
sprites.bg.fog = {}
sprites.bg.fog[1] = love.graphics.newImage('sprites/backgrounds/fog/layer1.png')
sprites.bg.fog2 = {}
sprites.bg.fog2[1] = love.graphics.newImage('sprites/backgrounds/fog2/layer1.png')
sprites.bg.fog3 = {}
sprites.bg.fog3[1] = love.graphics.newImage('sprites/backgrounds/fog3/layer1.png')
sprites.shadows = {} -- new folder created 11/1/2023
sprites.shadows.bigTree = love.graphics.newImage('sprites/shadows/bigTree.png')
sprites.shadows.chestBig = love.graphics.newImage('sprites/shadows/chestBig.png')
sprites.shadows.chestSmall = love.graphics.newImage('sprites/shadows/chestSmall.png')
sprites.shadows.longWeapon = love.graphics.newImage('sprites/shadows/longWeapon.png')
sprites.shadows.pillar = love.graphics.newImage('sprites/shadows/pillar.png')
sprites.shadows.npc = love.graphics.newImage('sprites/shadows/npc.png')
sprites.shadows.rectS = love.graphics.newImage('sprites/shadows/rectS.png')
sprites.shadows.rectXS = love.graphics.newImage('sprites/shadows/rectXS.png')
sprites.shadows.rectXXS = love.graphics.newImage('sprites/shadows/rectXXS.png')
sprites.shadows.rectWideS = love.graphics.newImage('sprites/shadows/rectWideS.png')
sprites.shadows.roundL = love.graphics.newImage('sprites/shadows/roundL.png')
sprites.shadows.roundM = love.graphics.newImage('sprites/shadows/roundM.png')
sprites.shadows.roundS = love.graphics.newImage('sprites/shadows/roundS.png')
sprites.shadows.roundXL = love.graphics.newImage('sprites/shadows/roundXL.png')
sprites.shadows.roundXS = love.graphics.newImage('sprites/shadows/roundXS.png')
sprites.shadows.roundXXS = love.graphics.newImage('sprites/shadows/roundXXS.png')
sprites.shadows.wideL = love.graphics.newImage('sprites/shadows/wideL.png')
sprites.shadows.wideXS = love.graphics.newImage('sprites/shadows/wideXS.png')
sprites.shadows.squareM = love.graphics.newImage('sprites/shadows/squareM.png')

-- since fonts are influenced by scale, they need to be re-initialized when the scale changes
function initFonts(sc)
    local fntSc = scale
    if sc then fntSc = sc else
        if gamestate < 1 then fntSc = scale * mainMenuScaleFactor end
        if pause and pause.state > 0 then fntSc = pause.scale end
    end
    fonts = {}
    fonts.debug = love.graphics.newFont("fonts/vt323/VT323-Regular.ttf", 6*fntSc)
    fonts.debug2 = love.graphics.newFont(10*fntSc)
    fonts.debugSmall = love.graphics.newFont("fonts/vt323/VT323-Regular.ttf", 10*fntSc)
    fonts.ammo = love.graphics.newFont("fonts/kenney-pixel-square/Kenney-Pixel-Square.ttf", 4.5*fntSc)
    fonts.coins = love.graphics.newFont("fonts/kenney-pixel-square/Kenney-Pixel-Square.ttf", 6.5*fntSc)
    fonts.shop = love.graphics.newFont("fonts/kenney-pixel-square/Kenney-Pixel-Square.ttf", 8)
    fonts.newDebug = love.graphics.newFont("fonts/raccoon/RaccoonSerif-Medium.ttf", 8*fntSc)

    --fonts.damage = love.graphics.newFont("fonts/magofonts/mago3.ttf", 16)
    --fonts.damage:setFilter( "nearest", "nearest" )
    fonts.damage = love.graphics.newFont("fonts/m6x11.ttf", 16)
    fonts.damage:setFilter( "nearest", "nearest" )
    fonts.tempMessage = love.graphics.newFont("fonts/magofonts/mago1.ttf", 16)
    fonts.tempMessage:setFilter( "nearest", "nearest" )
    fonts.damageText = love.graphics.newFont("fonts/magofonts/mago2.ttf", 16)

    fonts.menu = love.graphics.newFont("fonts/magofonts/mago1.ttf", 13*fntSc)
    fonts.menu:setFilter( "nearest", "nearest" )
    fonts.menuSmall = love.graphics.newFont("fonts/magofonts/mago1.ttf", 13*fntSc)
    fonts.menuSmall:setFilter( "nearest", "nearest" )
    fonts.settings = love.graphics.newFont("fonts/magofonts/mago1.ttf", 12*fntSc)
    fonts.settings:setFilter( "nearest", "nearest" )

    fonts.savedMessage = love.graphics.newFont("fonts/magofonts/mago3.ttf", 16)
    fonts.extraMessage = love.graphics.newFont("fonts/magofonts/mago1.ttf", 16)
    fonts.resourceCount = love.graphics.newFont("fonts/magofonts/mago3.ttf", 16)

    fonts.tutorial = love.graphics.newFont("fonts/1980v23P01.ttf", 16)

    fonts.gemTitle = love.graphics.newFont("fonts/1980v23P01.ttf", 16*fntSc)
    fonts.gemDesc = love.graphics.newFont("fonts/VGATypewriter.ttf", 10*fntSc)

    fonts.dungeonTitle = love.graphics.newFont("fonts/magofonts/mago1.ttf", 22*fntSc)
    fonts.dungeonTitle:setFilter( "nearest", "nearest" )

    fonts.pause1 = love.graphics.newFont("fonts/vt323/VT323-Regular.ttf", 12*fntSc)
    fonts.pause2 = love.graphics.newFont("fonts/vt323/VT323-Regular.ttf", 9*fntSc)
    fonts.pauseTop = love.graphics.newFont("fonts/vt323/VT323-Regular.ttf", 10*fntSc)

    fonts.hud = {}
    fonts.hud.bossTitle = love.graphics.newFont("fonts/magofonts/mago1.ttf", 10*fntSc)
    fonts.hud.bossTitle:setFilter( "nearest", "nearest" )
    fonts.hud.playerHealth = love.graphics.newFont("fonts/magofonts/mago1.ttf", 7.5*fntSc)
    fonts.hud.timer = love.graphics.newFont("fonts/magofonts/mago1.ttf", 14*fntSc)
    fonts.hud.health = love.graphics.newFont("fonts/1980v23P01.ttf", 18*fntSc)
    fonts.hud.ammo = love.graphics.newFont("fonts/magofonts/mago2.ttf", 16*fntSc)

    fonts.mainMenu = {}
    fonts.mainMenu.fileTitle = love.graphics.newFont("fonts/1980v23P01.ttf", 15*fntSc)
    fonts.mainMenu.fileStart = love.graphics.newFont("fonts/magofonts/mago1.ttf", 10*fntSc)
    fonts.mainMenu.story = love.graphics.newFont("fonts/nico/NicoClean-Regular.ttf", 7*fntSc)
    fonts.mainMenu.extra = love.graphics.newFont("fonts/1980v23P01.ttf", 13.5*fntSc)
    fonts.mainMenu.extraSmall = love.graphics.newFont("fonts/1980v23P01.ttf", 12*fntSc)
    fonts.mainMenu.altStory = love.graphics.newFont("fonts/nico/NicoClean-Regular.ttf", 5.5*fntSc)

    fonts.mainMenu.creditsTitle = love.graphics.newFont("fonts/nico/NicoClean-Regular.ttf", 10*fntSc)
    fonts.mainMenu.creditsHeading = love.graphics.newFont("fonts/raccoon/RaccoonSerif-Medium.ttf", 5*fntSc)
    fonts.mainMenu.creditsSub = love.graphics.newFont("fonts/raccoon/RaccoonSerif-Medium.ttf", 5*fntSc)
    fonts.mainMenu.creditsSubBold = love.graphics.newFont("fonts/raccoon/RaccoonSerif-Bold.ttf", 5*fntSc)

    fonts.newMenu = {}
    fonts.newMenu.start = love.graphics.newFont("fonts/inexpugnableExtended.ttf", 9.5*fntSc)
    fonts.newMenu.main = love.graphics.newFont("fonts/1980v23P01.ttf", 16*fntSc)
    fonts.newMenu.title = love.graphics.newFont("fonts/VGATypewriter.ttf", 12*fntSc)
    fonts.newMenu.flavor = love.graphics.newFont("fonts/VGATypewriter.ttf", 9*fntSc)
    fonts.newMenu.mode = love.graphics.newFont("fonts/VGATypewriter.ttf", 12*fntSc)
    fonts.newMenu.newGameStart = love.graphics.newFont("fonts/VGATypewriter.ttf", 15*fntSc)
    fonts.newMenu.back = love.graphics.newFont("fonts/VGATypewriter.ttf", 10*fntSc)
    fonts.newMenu.default = love.graphics.newFont("fonts/VGATypewriter.ttf", 8*fntSc)
    fonts.newMenu.fileTitle = love.graphics.newFont("fonts/1980v23P01.ttf", 16*fntSc)
    fonts.newMenu.fileStats = love.graphics.newFont("fonts/1980v23P01.ttf", 16*fntSc)
    fonts.newMenu.fileLastSave = love.graphics.newFont("fonts/1980v23P01.ttf", 16*fntSc)
    fonts.newMenu.add = love.graphics.newFont("fonts/magofonts/mago1.ttf", 16*fntSc)
    fonts.newMenu.settings = love.graphics.newFont("fonts/VGATypewriter.ttf", 7*fntSc)
    fonts.newMenu.keybindsTitle = love.graphics.newFont("fonts/VGATypewriter.ttf", 9*fntSc)
    fonts.newMenu.keybind = love.graphics.newFont("fonts/magofonts/mago1.ttf", 8*fntSc)
    --fonts.newMenu.intro = love.graphics.newFont("fonts/omelette/om_tall_plain.ttf", 9.5*fntSc)
    --fonts.newMenu.intro = love.graphics.newFont("fonts/1980v23P01.ttf", 12*fntSc)
    fonts.newMenu.intro = love.graphics.newFont("fonts/magofonts/mago1.ttf", 10.5*fntSc)
    fonts.newMenu.cycle = love.graphics.newFont("fonts/VGATypewriter.ttf", 9*fntSc)
    fonts.newMenu.debug = love.graphics.newFont("fonts/VGATypewriter.ttf", 9*fntSc)

    fonts.credits = {}
    fonts.credits.title = love.graphics.newFont("fonts/VGATypewriter.ttf", 12*fntSc)
    fonts.credits.subtitle = love.graphics.newFont("fonts/VGATypewriter.ttf", 10*fntSc)
    fonts.credits.subsubtitle = love.graphics.newFont("fonts/VGATypewriter.ttf", 8*fntSc)
    fonts.credits.tiny = love.graphics.newFont("fonts/VGATypewriter.ttf", 6*fntSc)
    fonts.credits.name = love.graphics.newFont("fonts/VGATypewriter.ttf", 7*fntSc)

    local pauseSc = scale
    if pause and pause.scale then pauseSc = pause.scale end
    fonts.pause = {}
    fonts.pause.text = love.graphics.newFont("fonts/magofonts/mago1.ttf", 11*pauseSc)
    fonts.pause.smallText = love.graphics.newFont("fonts/magofonts/mago1.ttf", 8*pauseSc)
    fonts.pause.settings = love.graphics.newFont("fonts/magofonts/mago1.ttf", 14*pauseSc)
    fonts.pause.settingsButton = love.graphics.newFont("fonts/magofonts/mago1.ttf", 12*pauseSc)
    fonts.pause.keybind = love.graphics.newFont("fonts/magofonts/mago1.ttf", 7*pauseSc)
    fonts.pause.keybindTitle = love.graphics.newFont("fonts/magofonts/mago3.ttf", 7*pauseSc)
    fonts.pause.money = love.graphics.newFont("fonts/omelette/om_tall_plain.ttf", 9*pauseSc)
    fonts.pause.title = love.graphics.newFont("fonts/1980v23P01.ttf", 14.5*pauseSc)
    fonts.pause.jewelryTitle = love.graphics.newFont("fonts/omelette/om_tall_plain.ttf", 7*pauseSc)
    fonts.pause.jewelryDesc = love.graphics.newFont("fonts/omelette/om_tall_plain.ttf", 5*pauseSc)
    fonts.pause.multiTitle = love.graphics.newFont("fonts/1980v23P01.ttf", 11*pauseSc)
    fonts.pause.message = love.graphics.newFont("fonts/VGATypewriter.ttf", 9*pauseSc)
    fonts.pause.messageSm = love.graphics.newFont("fonts/VGATypewriter.ttf", 7.5*pauseSc)

    fonts.pause.resourceCount = love.graphics.newFont("fonts/m5x7.ttf", 15*pauseSc)

    fonts.dialogue = {}
    fonts.dialogue.text = love.graphics.newFont("fonts/magofonts/mago1.ttf", 12.25*fntSc)
    fonts.dialogue.text2 = love.graphics.newFont("fonts/omelette/om_tall_plain.ttf", 9.5*fntSc)
    fonts.dialogue.text3 = love.graphics.newFont("fonts/monogram-extended.ttf", 13.5*fntSc)
    fonts.dialogue.answer = love.graphics.newFont("fonts/magofonts/mago1.ttf", 15.5*fntSc)

    fonts.misc = {}
    fonts.misc.minigame = love.graphics.newFont("fonts/omelette/om_tall_plain.ttf", 16) -- don't scale if it's in-camera
    fonts.misc.hopeText = love.graphics.newFont("fonts/omelette/om_tall_plain.ttf", 9.5*fntSc)
end
initFonts()

sounds = {}
sounds.effects = {}
sounds.effects.portalOpen = 'sounds/effects/portal-open.ogg'
sounds.effects.portalClose = 'sounds/effects/portal-close2.ogg'
sounds.effects.portalIntro = 'sounds/effects/portal-close1.ogg'
sounds.effects.ambience1 = 'sounds/effects/ambience1.ogg'
sounds.effects.ambience2 = 'sounds/effects/ambience2.ogg'
sounds.effects.electricBurst = 'sounds/effects/electricBurst.ogg'
sounds.effects.plugCharge = 'sounds/effects/plugCharge.ogg'
sounds.effects.plugUncharge = 'sounds/effects/plugUncharge.ogg'
sounds.effects.smallFall = 'sounds/effects/smallFall.ogg'
sounds.effects.poisonBlast = 'sounds/effects/poisonBlast.ogg'
sounds.effects.electricCast = 'sounds/effects/electricCast2.ogg'
sounds.effects.electricExplode = 'sounds/effects/electricExplode.ogg'
sounds.effects.explosion = 'sounds/effects/explosion.ogg'
sounds.effects.windSlam = 'sounds/effects/windSlam.ogg'
sounds.effects.spawnBig = 'sounds/effects/spawnBig.ogg'
sounds.effects.flowerGrow = 'sounds/effects/flowerGrow.ogg'
sounds.effects.crash = 'sounds/effects/crash.ogg'
sounds.effects.bubble = 'sounds/effects/bubble.ogg'
sounds.enemies = {}
sounds.enemies.die = 'sounds/enemies/enemyDie.wav'
sounds.enemies.hurt = 'sounds/enemies/enemyHurt.wav'
sounds.enemies.projectile = 'sounds/enemies/projectile.wav'
sounds.enemies.laser = 'sounds/enemies/laser.wav'
sounds.enemies.rockSurge = 'sounds/enemies/rock_surge.wav'
sounds.enemies.rockHit = 'sounds/enemies/rock_hit.wav'
sounds.enemies.roarCrushed = 'sounds/enemies/roar-crushed.ogg'
sounds.enemies.impact1 = 'sounds/enemies/impact1.ogg'
sounds.enemies.impact2 = 'sounds/enemies/impact2.ogg'
sounds.enemies.impact3 = 'sounds/enemies/impact3.ogg'
sounds.enemies.impact4 = 'sounds/enemies/impact4.ogg'
sounds.enemies.impact5 = 'sounds/enemies/impact5.ogg'
sounds.enemies.impact6 = 'sounds/enemies/impact6.ogg'
sounds.enemies.impactHeavy = 'sounds/enemies/impactHeavy.ogg'
sounds.enemies.notice = 'sounds/enemies/notice.ogg'
sounds.enemies.alert = 'sounds/enemies/alert.ogg'
sounds.enemies.slime = 'sounds/enemies/slime.ogg'
sounds.enemies.summon = 'sounds/enemies/summon.ogg'
sounds.enemies.sparkSpawn = 'sounds/enemies/sparkSpawn.ogg'
sounds.enemies.hurtSmall = 'sounds/enemies/hurtSmall.ogg'
sounds.attacks = {}
sounds.attacks.slam = 'sounds/attacks/slam.ogg'
sounds.attacks.zap = 'sounds/attacks/zap.ogg'
sounds.attacks.slashWeak = 'sounds/attacks/slashWeak.ogg'
sounds.attacks.bug = 'sounds/attacks/bug.ogg'
sounds.attacks.bugRaise = 'sounds/attacks/windup/bugRaise.ogg'
sounds.attacks.dig = 'sounds/attacks/dig.ogg'
sounds.attacks.digDown = 'sounds/attacks/digDown.ogg'
sounds.attacks.heavySlam = 'sounds/attacks/heavySlam.ogg'
sounds.attacks.spit = 'sounds/attacks/spit.ogg'
sounds.attacks.wetExplode = 'sounds/attacks/wetExplode.ogg'
sounds.attacks.zapBig = 'sounds/attacks/zapBig.ogg'
sounds.attacks.zapDash = 'sounds/attacks/zapDash.ogg'
sounds.attacks.zapHuge = 'sounds/attacks/zapHuge.ogg'
sounds.attacks.spooky = 'sounds/attacks/spooky.ogg'
sounds.attacks.spooky2 = 'sounds/attacks/spooky2.ogg'
sounds.windup = {}
sounds.windup.bugRaise = 'sounds/attacks/windup/bugRaise.ogg'
sounds.windup.chargeLarge = 'sounds/attacks/windup/chargeLarge.ogg'
sounds.windup.chargeMedElec = 'sounds/attacks/windup/chargeMedElec.ogg'
sounds.windup.chargeLargeElec = 'sounds/attacks/windup/chargeLargeElec.ogg'
sounds.windup.magicCharge = 'sounds/attacks/windup/magicCharge.ogg'
sounds.windup.zapDashWindup = 'sounds/attacks/windup/zapDashWindup.ogg'
sounds.windup.spookyRise = 'sounds/attacks/windup/spookyRise.ogg'
sounds.windup.gross = 'sounds/attacks/windup/gross.ogg'
sounds.environment = {}
sounds.environment.collide = 'sounds/environment/collide.ogg'
sounds.environment.swordCollide = 'sounds/environment/swordCollide.ogg'
sounds.environment.land = 'sounds/environment/land.wav'
sounds.environment.splash = 'sounds/environment/splash.wav'
sounds.environment.thunder = 'sounds/environment/thunder.ogg'
sounds.environment.sprout = 'sounds/environment/sprout.ogg'
sounds.environment.vineSpike = 'sounds/environment/vineSpike.ogg'
sounds.environment.appleBreak = 'sounds/environment/appleBreak.ogg'
sounds.destroy = {}
sounds.destroy.crumble = 'sounds/destroy/crumble.ogg'
sounds.destroy.rock = 'sounds/destroy/rockBreak.wav'
sounds.destroy.torch = 'sounds/destroy/torch.wav'
sounds.destroy.potOld = 'sounds/destroy/potBreak.ogg'
sounds.destroy.demolish = 'sounds/destroy/demolish.ogg'
sounds.destroy.pot = 'sounds/destroy/pot.ogg'
sounds.destroy.box = 'sounds/destroy/box.ogg'
sounds.destroy.wood = 'sounds/destroy/wood.ogg'
sounds.destroy.shelf = 'sounds/destroy/shelf.ogg'
sounds.items = {}
sounds.items.arrow = 'sounds/items/arrow.wav'
sounds.items.boomerang = 'sounds/items/boomerang.wav'
sounds.items.chest = 'sounds/items/chest.ogg'
sounds.items.coin = 'sounds/items/coin-edit.wav'
sounds.items.explosion = 'sounds/items/explosion.wav'
sounds.items.fire = 'sounds/items/fire.wav'
sounds.items.grapple = 'sounds/items/grapple.wav'
sounds.items.set = 'sounds/items/set.wav'
sounds.items.sword = 'sounds/items/sword2.wav'
sounds.items.swordStab = 'sounds/items/sword1.wav'
sounds.items.swordExtra = 'sounds/items/sword.wav'
sounds.player = {}
sounds.player.hurt = 'sounds/player/playerHurt.wav'
sounds.player.roll = 'sounds/player/roll.wav'
sounds.player.splash = 'sounds/player/playerSplash.wav'
sounds.player.recoil = 'sounds/player/recoil.wav'
sounds.player.throw = 'sounds/player/throw.wav'
sounds.player.shocked = 'sounds/player/shocked.ogg'
sounds.player.fall = 'sounds/player/fall.ogg'
sounds.player.die = 'sounds/player/die.ogg'
sounds.player.dieLand = 'sounds/player/die-land.ogg'
sounds.player.itemGet = 'sounds/player/itemGet.ogg'
sounds.player.equip = 'sounds/player/equip.ogg'
sounds.player.unequip = 'sounds/player/unequip.ogg'
sounds.player.lowHealth = 'sounds/player/lowHealth.ogg'
sounds.player.charge = 'sounds/player/charge.ogg'
sounds.player.step = {}
sounds.player.step[1] = 'sounds/player/step/step1.ogg'
sounds.player.step[2] = 'sounds/player/step/step2.ogg'
sounds.player.step[3] = 'sounds/player/step/step3.ogg'
sounds.player.step[4] = 'sounds/player/step/step4.ogg'
sounds.player.step[5] = 'sounds/player/step/step5.ogg'
sounds.spells = {}
sounds.spells.lightning = 'sounds/spells/lightning.wav'
sounds.spells.thunder = 'sounds/spells/distant-thunder.mp3'
sounds.spells.fire = 'sounds/spells/fire.wav'
sounds.spells.iceShards = 'sounds/spells/ice-shards.wav'
sounds.spells.heal = 'sounds/spells/heal.ogg'
sounds.spells.minorHeal = 'sounds/spells/minorHeal.ogg'
sounds.ui = {}
sounds.ui.menuOpen = 'sounds/ui/menu-open.ogg'
sounds.ui.menuClose = 'sounds/ui/menu-close.ogg'
sounds.ui.mapOpen = 'sounds/ui/mapOpen.ogg'
sounds.ui.mapClose = 'sounds/ui/mapClose.ogg'
sounds.ui.text = 'sounds/ui/text3.ogg'
sounds.ui.move = 'sounds/ui/move.ogg'
sounds.ui.fantasyClick = 'sounds/ui/fantasy-click.ogg'
sounds.ui.hoverChange = 'sounds/ui/hoverChange3.ogg'
sounds.ui.confirm = 'sounds/ui/confirm.ogg'
sounds.ui.menuShift = 'sounds/ui/menuShift.ogg'
sounds.misc = {}
sounds.misc.alarm = 'sounds/misc/alarm.ogg'
sounds.misc.ascendLong = 'sounds/misc/ascendLong.ogg'
sounds.misc.ascendSoft = 'sounds/misc/ascendSoft.ogg'
sounds.misc.challengeComplete = 'sounds/misc/challengeComplete.ogg'
sounds.misc.cinematicHit = 'sounds/misc/cinematicHit.ogg'
sounds.misc.countdown = 'sounds/misc/countdown.ogg'
sounds.misc.countdownFinal = 'sounds/misc/countdownFinal.ogg'
sounds.misc.teleport = 'sounds/misc/teleport.wav'
sounds.misc.purchase = 'sounds/misc/purchase.wav'
sounds.misc.save = 'sounds/misc/save.wav'
sounds.misc.elevatorActivate = 'sounds/misc/elevatorActivate.ogg'
sounds.misc.elevatorStop = 'sounds/misc/elevatorStop.ogg'
sounds.misc.elevatorRise = 'sounds/misc/elevatorRise.ogg'
sounds.misc.elevatorRise2 = 'sounds/misc/elevatorRise2.wav'
sounds.misc.elevatorFall = 'sounds/misc/elevatorFall.ogg'
sounds.misc.smith = 'sounds/misc/smith.ogg'
sounds.misc.success = 'sounds/misc/success.ogg'
sounds.misc.flee = 'sounds/misc/flee.ogg'
sounds.misc.techStartBig = 'sounds/misc/techStartBig.ogg'
sounds.misc.spookyStart = 'sounds/misc/spookyStart.ogg'
sounds.misc.statueSpeak = 'sounds/misc/statue-speak.ogg'
sounds.misc.statueShake = 'sounds/misc/statue-shake.ogg'
sounds.jewelry = {}
sounds.jewelry.lucky = 'sounds/jewelry/lucky2.ogg'
sounds.jewelry.critical = 'sounds/jewelry/critical.ogg'
sounds.jewelry.gemEquip = 'sounds/jewelry/gemEquip.ogg'
sounds.jewelry.gemRemove = 'sounds/jewelry/gemRemove.ogg'
sounds.weapons = {}
sounds.weapons.slash = 'sounds/weapons/slash.ogg'
sounds.weapons.stab = 'sounds/weapons/stab.ogg'
sounds.weapons.bigSlash = 'sounds/weapons/bigSlash.ogg'
sounds.weapons.bigStab = 'sounds/weapons/bigStab.ogg'
sounds.weapons.flame = 'sounds/weapons/flame.ogg'
sounds.weapons.fail = 'sounds/weapons/weaponFail.ogg'
sounds.weapons.breakFull = 'sounds/weapons/weaponBreak.ogg'
sounds.weapons.breakEmpty = 'sounds/weapons/weaponEmpty2.ogg'
sounds.weapons.shockBall = 'sounds/weapons/shockBall.wav'
sounds.weapons.electricCast = 'sounds/weapons/electricCast.ogg'
sounds.npc = {}
sounds.npc.hawk = 'sounds/npc/hawk.ogg'
sounds.resources = {}
sounds.resources.get = 'sounds/items/getResource.ogg'

sounds.ambience = {}
sounds.ambience.wind = 'sounds/ambience/wind.ogg'
sounds.ambience.rain = 'sounds/ambience/rain.ogg'

bgm = {}
bgm.mainMenu = 'music/mainMenu.ogg'
bgm.forest = 'music/forest.ogg'
bgm.town = 'music/town.ogg'
bgm.cave = 'music/cave.ogg'
bgm.frightening = 'music/frightening.ogg'
bgm.story = 'music/story.ogg'
bgm.cloudDungeon = 'music/cloudDungeon.ogg'
bgm.cloudBoss = 'music/cloudBossFull.ogg'
bgm.gameOver = 'music/game-over.ogg'
bgm.itemGet = 'music/item-get.ogg'
bgm.minigame = 'music/minigame.ogg'
bgm.flashback = 'music/flashback.ogg'
bgm.boss = 'music/bossBasic.ogg'
