function requireAll()

    require("src/startup/collisionClasses")
    createCollisionClasses()

    -- Load assets, data
    require("src/startup/assets")
    require("src/startup/data")
    
    require("src/utilities/cam")
    require("src/utilities/controls")
    require("src/utilities/debug")
    require("src/utilities/destroyAll")
    require("src/utilities/events")
    require("src/utilities/hitbox")
    require("src/utilities/misc")
    require("src/utilities/music")
    require("src/utilities/shaders")
    require("src/utilities/shake")
    require("src/utilities/speedrun")
    require("src/utilities/soundManager")
    require("src/utilities/spriteManager")
    require("src/utilities/timers")

    require("src/multiplayer/client")

    require("src/player/playerMain")
    require("src/player/playerAnim")
    require("src/player/playerDraw")
    require("src/player/playerUpdate")
    require("src/player/playerAttack")
    require("src/player/playerMagic")
    require("src/player/playerMove")

    require("src/update")
    require("src/draw")

    require("src/effects/blast")
    require("src/effects/damage")
    require("src/effects/effect")
    require("src/effects/effect2")
    require("src/effects/explosion")
    require("src/effects/rubble")
    require("src/effects/rubbleEvent")
    require("src/effects/shadows")
    require("src/effects/particles/particle")
    require("src/effects/particles/particleEvent")
    require("src/effects/background/parallax")
    require("src/effects/background/simplax")
    require("src/effects/background/background")

    require("src/enemies/enemy")
    require("src/enemies/projectile")
    require("src/enemies/lob")
    require("src/enemies/offscreen")

    require("src/environment/lightSource")
    require("src/environment/plant")
    require("src/environment/platform")
    require("src/environment/prop")
    require("src/environment/saveSpot")
    require("src/environment/sink")
    require("src/environment/soil")
    require("src/environment/structure")
    require("src/environment/tree")
    require("src/environment/water")
    require("src/environment/weather")
    require("src/environment/hazards/spikes")

    require("src/items/loot")
    require("src/items/star")
    require("src/items/grapple")
    require("src/items/chest")
    require("src/items/shopItem")
    require("src/items/jewelry")
    require("src/items/weapon")
    require("src/items/resource")

    require("src/spells/spells")
    require("src/spells/fireball")
    require("src/spells/flame")
    
    require("src/levels/cutscene")
    require("src/levels/challenge")
    require("src/levels/cover")
    require("src/levels/curtain")
    require("src/levels/elevator")
    require("src/levels/loadMap")
    require("src/levels/npc")
    require("src/levels/pin")
    require("src/levels/portal")
    require("src/levels/tileState")
    require("src/levels/transition")
    require("src/levels/tutorial")
    require("src/levels/wall")
    require("src/levels/procgen/level")
    require("src/levels/procgen/map")
    require("src/levels/procgen/mapData")
    require("src/levels/procgen/procgen")
    require("src/levels/procgen/room")

    require("src/ui/answer")
    require("src/ui/hud")
    require("src/ui/menu")
    require("src/ui/newui")
    require("src/ui/dialogue/infoPanel")
    require("src/ui/dialogue/dialogue")
    require("src/ui/dialogue/conversation")
    require("src/ui/dialogue/talk")
    require("src/ui/pause/pause")
    require("src/ui/pause/settings")
    require("src/ui/pause/button")

    require("src/stats/enemyStats")
    require("src/stats/bossStats")
    require("src/stats/narrationMaps")
    require("src/stats/npcMaps")
    require("src/stats/npcStats")
    require("src/stats/weaponStats")

end